name: Build, push Docker image and deploy to Azure

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Adding below tag any push to main as "latest"
      # To deploy latest, create a release with a semver tag
      # type=raw,value=latest,enable={{is_default_branch}}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # this is back a single image, `-with-proxy` is legacy and will be removed
          images: |
            ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.title=Wttr MCP Server
            org.opencontainers.image.description="Weather MCP Server"
            org.opencontainers.image.source=${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
