name: Build and package Azure Functions for deployment

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: write

jobs:
  push_azure_functions_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Azure Functions package
        run: |
          cd weather-function
          zip -r ../azure-functions-package.zip . -x "*.git*" "*.vscode*" "__pycache__/*" "*.pyc"
          cd ..
        shell: bash

      - name: Upload Azure Functions artifact
        uses: actions/upload-artifact@v4
        with:
          name: azure-functions-package
          path: azure-functions-package.zip
          retention-days: 30